/**
 * Generated by supertag-cli codegen
 * DO NOT EDIT - This file is auto-generated
 *
 * To regenerate with your actual Todo supertag:
 *   supertag codegen generate -o ./src/schemas.ts --tags Todo
 *
 * This is a sample schema for demonstration purposes.
 */

import { Schema } from "effect";

/**
 * Todo schema - represents a task item from Tana
 *
 * This schema demonstrates Effect Schema.Class usage with optional fields
 * using the "option" strategy (Schema.optionalWith with { as: "Option" }).
 */
export class Todo extends Schema.Class<Todo>("Todo")({
  /** Tana node ID */
  id: Schema.String,

  /** Todo title/name */
  title: Schema.optionalWith(Schema.String, { as: "Option" }),

  /** Due date for the todo */
  dueDate: Schema.optionalWith(Schema.DateFromString, { as: "Option" }),

  /** Whether the todo is completed */
  completed: Schema.optionalWith(Schema.Boolean, { as: "Option" }),

  /** Current status (e.g., "active", "waiting", "done") */
  status: Schema.optionalWith(Schema.String, { as: "Option" }),

  /** Priority level (e.g., "high", "medium", "low") */
  priority: Schema.optionalWith(Schema.String, { as: "Option" }),
}) {}

/**
 * Input type for creating new todos (used with Tana Input API)
 */
export class TodoInput extends Schema.Class<TodoInput>("TodoInput")({
  /** Todo title (required for creation) */
  title: Schema.String,

  /** Optional due date */
  dueDate: Schema.optionalWith(Schema.String, { as: "Option" }),

  /** Optional priority */
  priority: Schema.optionalWith(Schema.String, { as: "Option" }),
}) {}

/**
 * Decode unknown data into a Todo
 */
export const decodeTodo = Schema.decodeUnknown(Todo);

/**
 * Decode unknown data into a TodoInput
 */
export const decodeTodoInput = Schema.decodeUnknown(TodoInput);
